
verdir : "/ec/res4/scratch/snh/monitor/data/"

experiments:
   obs:
     input_path : "/hpcperm/snh/hm_home/spd_68abb65f_gnu_dbl/parchive/archive/extract"
     is_vfld : false
   spd_68abb65f_gnu_dbl:
     input_path : "/hpcperm/snh/hm_home/spd_68abb65f_gnu_dbl/parchive/archive/extract"
   spd_68abb65f_gnu_sp:
     input_path : "/hpcperm/snh/hm_home/spd_68abb65f_gnu_sp/parchive/archive/extract"
   spd_68abb65f_intel_dbl:
     input_path : "/hpcperm/snh/hm_home/spd_68abb65f_intel_dbl/parchive/archive/extract"
   spd_68abb65f_intel_dbl_noawx:
     input_path : "/hpcperm/snh/hm_home/spd_68abb65f_intel_dbl_noawx/parchive/archive/extract"
   spd_68abb65f_intel_sp:
     input_path : "/hpcperm/snh/hm_home/spd_68abb65f_intel_sp/parchive/archive/extract"
   spd_68abb65f_intel_sp_noawx:
     input_path : "/hpcperm/snh/hm_home/spd_68abb65f_intel_sp_noawx/parchive/archive/extract"
